- hosts: demo
  become: true
  tasks:
  - name: Install git, maven 
    package: name={{item}} state=present
    loop:
     - git
     - maven
  - name: Clone the code on the worker nodes from github
    git: repo=https://github.com/harapriya16/CEP-Ansible-1.git dest=/tmp/test
  - name: Execute maven command to build the code
      - name: Clone the code on the worker nodes from github
    ommand: chdir=/tmp/test mvn package
    
